/**
 * qrAuth.js — "Login To Netmon" and "Scan To Login", ported from the Android
 * CRM app's dashboard overflow menu (menu_item.xml → DashboardLatest.java).
 *
 * TWO THINGS HERE ARE UNLIKE EVERY OTHER CALL IN THIS APP.
 *
 * 1. THE PATH IS THE DOMAIN ROOT, not the API base.
 *    Every other endpoint hangs off `getBaseUrl()` (…/prod/ or …/netmon/).
 *    These two do not — Android declares them as bare
 *    `@POST("QrcodeAuthentication/verifyqrcode")` against the Retrofit base
 *    host, i.e. `{origin}/QrcodeAuthentication/…` with no `prod/` segment
 *    (ApiInterface.java:970,977). Calling them under the API base returns a
 *    404 HTML page, which JSON.parse then reports as a transport error.
 *
 * 2. err_code IS INVERTED ON BOTH ENDPOINTS.
 *    Success is `err_code === 1`, failure is `0` — the opposite of the rest of
 *    the backend. Android gets apploginlink right (DashboardLatest.java:627)
 *    but verifyqrcode WRONG: it checks `err_code == 0`
 *    (DashboardLatest.java:618), which is the FAILURE value. So the Android app
 *    announces "Web Login Success" for a rejected scan and says nothing at all
 *    when the login is genuinely approved. Do not copy that check.
 *
 *    Proven end-to-end 2026-08-19 by minting a real QR from
 *    QrcodeAuthentication/getqrcode and posting its token:
 *      valid token → {"err_code":1, body:{token:"$2y$10$…", verified:1}}
 *      bogus token → {"err_code":0, err_msg:"Invalid Token",   body:null}
 *      wrong user  → {"err_code":0, err_msg:"Invalid username", body:null}
 *
 * They also use a third credential set (VITE_WEBLOGIN_*), distinct from the
 * main and internet-payment blocks, and send NO appkeytype/appversion header.
 *
 * Contracts verified live 2026-08-17 against bbnlnetmon and bbnlpwa:
 *
 *   apploginlink  {reference_type:"netmon_login", reference:"<operator>"}
 *     → {status:{err_code:1,err_msg:""}, body:{link:"{origin}/prod/login?q=…"}}
 *     → {status:{err_code:0,err_msg:"Invalid username"}, body:[]}
 *
 *   verifyqrcode  {reference_type:"employer", reference:"<operator>", token}
 *     → {status:{err_code:1,err_msg:""}, body:{token, verified:1}}   SUCCESS
 *     → {status:{err_code:0,err_msg:"Invalid Token"}, body:null}     failure
 *
 *   NOTE the reference_type differs per endpoint: "netmon_login" for the SSO
 *   link, "employer" for the QR approval (DashboardLatest.java:91,542). They
 *   are not interchangeable — sending the wrong one yields "Invalid request".
 *
 * SECURITY: the link apploginlink returns is a BEARER CREDENTIAL. Anyone
 * holding that URL is signed in as the operator. It must never be logged,
 * stored, put in analytics, or rendered as copyable text — hand it straight to
 * the browser and drop the reference.
 */

import { getBaseUrl, apiFetch } from "./apiCore";

/** Success on apploginlink — inverted relative to the rest of the backend. */
const NETMON_OK = 1;

/**
 * Origin of the API host, with any base path stripped. Used only by the
 * link-alignment fallback now that requests go through the same-origin proxy.
 *
 * getBaseUrl() is e.g. "https://bbnlpwa.bbnl.in/prod/"; these endpoints need
 * "https://bbnlpwa.bbnl.in/". Falls back to the page origin if the configured
 * base is relative (dev proxy paths), which keeps the call same-origin.
 */
export function getWebLoginOrigin() {
    const base = String(getBaseUrl() || "");
    try {
        return new URL(base, typeof window !== "undefined" ? window.location.href : undefined).origin;
    } catch (_) {
        return typeof window !== "undefined" ? window.location.origin : "";
    }
}

/**
 * Where the QR service is reached: a SAME-ORIGIN path that Apache proxies.
 *
 * Not called directly, and the credentials are not sent from here — see the
 * casing note in postWebLogin. `.htaccess` (generated by vite.config.js)
 * forwards {base}qr-api/* to {apiOrigin}/QrcodeAuthentication/* and attaches
 * Authorization / username / password with the exact casing the service
 * demands. That also keeps those secrets out of the JS bundle.
 */
function qrProxyUrl(path) {
    const base = String(import.meta.env.VITE_API_APP_DIR_PATH || "/");
    const prefix = base.endsWith("/") ? base : `${base}/`;
    return `${prefix}qr-api/${path}`;
}

async function postWebLogin(path, payload, label) {
    const url = qrProxyUrl(path);
    const resp = await apiFetch(
        url,
        {
            method: "POST",
            // NO credential headers. The QrcodeAuthentication service matches
            // them CASE-SENSITIVELY (only `Authorization`, `username`,
            // `password`), and browsers always lowercase header names — the
            // Fetch API normalises them and JavaScript cannot override it. So
            // no value sent from here can ever satisfy it. Apache attaches
            // them on the way through instead.
            //
            // Measured 2026-08-19 on an otherwise identical request:
            //   Authorization/username/password → {"err_code":1,…,"link":…}
            //   authorization/username/password → failed   (HTTP 200!)
            // Credentials in the body, in the query string, and as X- headers
            // were all rejected too, so proxying is the only client-side fix.
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
        },
        label
    );

    if (resp.status === 502) {
        // The .htaccess rule fires this when mod_proxy is missing, rather than
        // letting the SPA fallback answer with an HTML shell.
        throw new Error(
            "Netmon sign-in is not reachable: the qr-api proxy is not enabled on this server " +
            "(needs mod_proxy + mod_headers)."
        );
    }
    if (resp.status === 404) {
        throw new Error(
            "Netmon sign-in is not reachable: the qr-api proxy rule is missing. " +
            "Re-deploy including the .htaccess from this build."
        );
    }
    if (!resp.ok) throw new Error(`${label}: HTTP ${resp.status}`);

    // THIS ENDPOINT DOES NOT ALWAYS RETURN JSON. On a credential mismatch it
    // answers with the bare body `failed` — at HTTP 200, Content-Type
    // text/html — so neither resp.ok nor the content type gives it away, and
    // resp.json() would throw "Unexpected token 'i', \"failed\" is not valid
    // JSON" straight into a toast.
    const text = await resp.text();
    const trimmed = text.trim();

    // THE SPA SHELL CAME BACK. The 404/502 branches above only fire when the
    // qr-api rules are present-but-broken. When the deployed .htaccess predates
    // those rules entirely, `qr-api/apploginlink` is just an unmatched path: it
    // is neither a file nor a directory, so the SPA fallback rewrites it to
    // index.html and Apache answers HTTP 200 with an HTML body. Nothing above
    // catches that, and JSON.parse then reported it as
    //   Netmon returned an unexpected response: "<!doctype html> <html lang=…"
    // which names the wrong culprit entirely.
    //
    // Measured 2026-08-24 against the live deployments:
    //   netmontest.bbnl.in/pwa/crm/qr-api/apploginlink      → 154 bytes of JSON
    //   bbnlnetmon.bbnl.in/smartphone/crm/qr-api/apploginlink → 8936 bytes of HTML
    //   bbnlpwa.bbnl.in/smartphone/crm/qr-api/apploginlink    → 8936 bytes of HTML
    // Both production hosts were still serving a 3 Aug bundle, built before the
    // qr-api rules existed. That is the whole reason both menu items fail there.
    if (/^<(?:!doctype|html|\?xml)/i.test(trimmed)) {
        throw new Error(
            "Netmon sign-in is not reachable: this deployment is missing the qr-api proxy rule, " +
            "so the request was answered with the app itself. Re-deploy including the .htaccess " +
            "from this build."
        );
    }

    if (/^failed$/i.test(trimmed)) {
        // Reaching this now means the proxy forwarded the request but did not
        // attach the credentials — mod_headers missing, or the RequestHeader
        // lines absent from the deployed .htaccess.
        try {
            console.error(
                "[netmon] proxy reached the service but credentials were not attached. " +
                "Check mod_headers is loaded and the RequestHeader lines are present in " +
                "the deployed .htaccess.",
                { url }
            );
        } catch (_) {}
        throw new Error(
            "Netmon rejected sign-in: the server proxy did not attach credentials " +
            "(check mod_headers and the deployed .htaccess)."
        );
    }

    try {
        return JSON.parse(trimmed);
    } catch (_) {
        const excerpt = trimmed.replace(/\s+/g, " ").slice(0, 80);
        throw new Error(`Netmon returned an unexpected response: "${excerpt}"`);
    }
}

/**
 * Decode the payload of a scanned "Scan To Login" QR code.
 *
 * The netmon web login page renders a base64-encoded JSON blob carrying the
 * challenge token; Android base64-decodes the scanned string and Gson-parses
 * it into QRWebLoginRequest (DashboardLatest.java:508-513). Only `token` is
 * taken from it — reference_type and reference are supplied by the app, so a
 * tampered QR cannot redirect the approval at somebody else's account.
 *
 * @param {string} scanned raw text from the scanner
 * @returns {string} the token, or "" if the payload is not a valid QR login
 */
export function decodeQrLoginToken(scanned) {
    const raw = String(scanned || "").trim();
    if (!raw) return "";
    try {
        const json = typeof atob === "function"
            ? decodeURIComponent(escape(atob(raw)))
            : Buffer.from(raw, "base64").toString("utf8");
        const parsed = JSON.parse(json);
        return String(parsed?.token || "");
    } catch (_) {
        // Not base64 JSON. Some scanners hand back the token directly, so
        // accept a bare token rather than failing a legitimate scan — the
        // backend rejects anything it does not recognise ("Invalid Token").
        return /^[\w$./+=-]{16,}$/.test(raw) ? raw : "";
    }
}

/**
 * Point the returned login URL at THIS environment's netmon console.
 *
 * The QR service mints the token (only it can), but it builds the link from a
 * hardcoded `/prod/` path plus whatever host the request arrived on. That is
 * right on production and wrong everywhere else. Measured 2026-08-19 — the
 * SAME token, two hosts:
 *
 *   POST http://124.40.244.211/QrcodeAuthentication/apploginlink
 *     → http://124.40.244.211/netmon/login?q=$2y$10$nMQAXirq…      correct
 *   POST https://netmontest.bbnl.in/QrcodeAuthentication/apploginlink
 *     → https://netmontest.bbnl.in/prod/login?q=$2y$10$nMQAXirq…   /prod/ 404s
 *
 * So the TOKEN is taken from the response and the DESTINATION from
 * VITE_NETMON_CONSOLE_URL, which names the console for the environment this
 * build targets. For testing that is `http://124.40.244.211/netmon/login`,
 * confirmed by the team and matching Android's own (commented-out) testing
 * block in Constants.java.
 *
 * THE HOSTNAME IN THAT VALUE IS NOT INTERCHANGEABLE WITH THE IP, even though
 * both reach the same machine. netmon chooses which QR database to look the
 * token up in from its OWN base_url (Login.php::qrDatabase()):
 *
 *   base_url in ('http://localhost/netmon/', 'http://124.40.244.211/netmon/')
 *       ? 172.16.59.111   <- test QR database
 *       : 172.16.59.114   <- PRODUCTION QR database
 *
 * `netmontest.bbnl.in` was never added to that list, so netmon reached by that
 * hostname searches the production database while QrcodeAuthentication on the
 * same box wrote the token to the test one. Measured 2026-08-24, ONE token
 * minted at netmontest.bbnl.in:
 *   https://netmontest.bbnl.in/netmon/login?q=…  → 307 back to /netmon/login  rejected
 *   http://124.40.244.211/netmon/login?q=…       → 307 to /netmon/user/list   signed in
 * Setting this to the hostname is therefore a silent, total failure of "Login
 * To Netmon" on test. Production is unaffected — bbnlnetmon and bbnlpwa both
 * mint and redeem in 172.16.59.114 (verified end to end the same day).
 *
 * The same split breaks "Scan To Login" on test, and that half CANNOT be fixed
 * here: the login page polls Login/getQrcode, which reads the token through
 * the same qrDatabase(), so an approval this app writes to the test database
 * is invisible to a page served from netmontest.bbnl.in. Confirmed 2026-08-24
 * by scanning a real QR from that page — verifyqrcode answered
 * {err_code:1, verified:1} and the page kept polling an empty image forever.
 * The identical run against bbnlnetmon.bbnl.in/prod/login returned "success".
 * Fixing test needs the backend host list updated; nothing in the PWA can.
 *
 * The console may be plain http:// while the app is https://. That is fine:
 * this URL is handed to window.open as a top-level navigation, not fetched, so
 * it is not mixed content. The token itself is still minted over HTTPS,
 * same-origin — which matters because NONE of these endpoints send CORS
 * headers, so a cross-origin fetch to them is blocked outright.
 *
 * With no console configured, falls back to keeping the backend's host and
 * substituting our own API base path — the previous behaviour.
 */
export function alignNetmonLink(link) {
    const raw = String(link || "");
    if (!raw) return "";

    let target;
    try { target = new URL(raw); } catch (_) { return raw; }

    const configured = String(import.meta.env.VITE_NETMON_CONSOLE_URL || "").trim();
    if (configured) {
        try {
            const console_ = new URL(configured);
            // Carry the whole query across — `q` is the credential, and any
            // other parameter the service adds travels with it.
            console_.search = target.search;
            return console_.href;
        } catch (_) { /* misconfigured — fall through */ }
    }

    // No console configured: keep the backend's host, correct the path.
    let base;
    try {
        base = new URL(getBaseUrl(), typeof window !== "undefined" ? window.location.href : undefined);
    } catch (_) {
        return raw;
    }
    if (target.origin !== base.origin) return raw;
    const basePath = base.pathname.endsWith("/") ? base.pathname : `${base.pathname}/`;
    if (target.pathname.startsWith(basePath)) return raw;
    const page = target.pathname.split("/").filter(Boolean).pop() || "login";
    return `${target.origin}${basePath}${page}${target.search}`;
}

/**
 * Fetch a one-shot, pre-authenticated netmon web URL for this operator.
 *
 * @param {string} reference operator's app username (getUser().username) —
 *   the same value sent as `loginuname` to myWallet. Android reads it from the
 *   stored `app_username` pref (DashboardLatest.java:147,541).
 * @returns {Promise<{ok: boolean, link: string, message: string}>}
 */
export async function getNetmonLoginLink(reference) {
    const data = await postWebLogin(
        "apploginlink",
        { reference_type: "netmon_login", reference: String(reference || "") },
        "getNetmonLoginLink"
    );
    const ok = Number(data?.status?.err_code) === NETMON_OK;
    return {
        ok,
        link: ok ? alignNetmonLink(data?.body?.link) : "",
        // err_msg is empty on success; give the caller something to show.
        message: String(data?.status?.err_msg || (ok ? "" : "Could not open Netmon.")),
    };
}

/**
 * Approve a web login that was started on another device by scanning its QR.
 *
 * @param {{reference: string, token: string}} params
 * @returns {Promise<{ok: boolean, message: string}>}
 */
export async function verifyQrLogin({ reference, token }) {
    const data = await postWebLogin(
        "verifyqrcode",
        { reference_type: "employer", reference: String(reference || ""), token: String(token || "") },
        "verifyQrLogin"
    );

    // DO NOT copy Android's check here. It tests `err_code == 0`
    // (DashboardLatest.java:618) — which on this endpoint is the FAILURE
    // value, so the Android app reports "Web Login Success" for a scan the
    // backend rejected and stays silent when one actually succeeds.
    //
    // Verified end-to-end by minting a real QR from
    // QrcodeAuthentication/getqrcode and posting its token:
    //
    //   valid  → {"status":{"err_code":1,…},"body":{"token":"$2y$10$…","verified":1}}
    //   bogus  → {"status":{"err_code":0,"err_msg":"Invalid Token"},"body":null}
    //
    // Same inversion as apploginlink. The body is still required as well: a
    // populated {token, verified} is the only positive proof the backend
    // actually approved something.
    const body = data?.body;
    const errMsg = String(data?.status?.err_msg || "");
    const ok = Number(data?.status?.err_code) === NETMON_OK
        && !!body
        && !Array.isArray(body)
        && (body.verified === undefined || Boolean(Number(body.verified)));

    return {
        ok,
        message: ok
            ? "Web login approved — check the browser on your computer."
            // Surface the backend's own wording ("Invalid Token") when it gives one.
            : (errMsg && !/^success$/i.test(errMsg) ? errMsg : "Could not approve this login."),
    };
}
